api:
  version:
    url: /api/v1

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          charset_name: UTF-8
        default_schema: tickaboo
    show-sql: true
  flyway:
    default-schema: tickaboo
    schemas: tickaboo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
